### ISSUE TITLE
Non-scrolling footnotes

### ISSUE THREAD

**Issue by jphastings** [deliveroo/deliveroo.engineering#10]
A mechanism to show footnotes (of which we use many!) in a way that means you don't lose your place in the text would be very useful for longer articles.

**Comment by kapowaz** [comment]
The way Kramdown implements footnotes now also creates a fragment identifier link which takes you back to the place where the footnote link was, e.g.

![img](http://snap.kapowaz.net/ntd8x.png)

![img](http://snap.kapowaz.net/lo0ry.png)

Going to mark this as unneeded unless you feel strongly about this being literally sticky!
