### ISSUE TITLE
Make sidebars full-width on mobile

### ISSUE THREAD

**Issue by jphastings** [deliveroo/deliveroo.engineering#12]
Sidebars currently take X% of the screen width, regardless of the size of the browser. For mobile clients this makes both the body text and the sidebar text very hard to read. Let's get our responsive CSS on!

**Comment by kapowaz** [comment]
`<aside>` elements now float and occupy 40% of the main content width assuming a large enough breakpoint. At smaller breakpoints they swap out to 100% width.

Marking this as fixed by #46 😁
