### ISSUE TITLE
Gently "enforce" whitespace removal and common code formatting rules in guidelines source

### ISSUE THREAD

**Issue by xarisd** [deliveroo/deliveroo.engineering#122]
### Why?

To minimize annoying diffs and potential conflicts due to whitespace and code formatting in general.

A recent example of the problem is  #121 in which I've made a simple change (literally added a `-`).
Because of my editor setup to remove whitespace at the end of the line, there where changes in irrelevant lines.

### Possible solution 

We could use something like http://editorconfig.org/ to (try to) "enforce" it in non-critical repositories/projects such as this one.

Like, including a .editorconfig in the project root.

This way we will be lowering the barrier because most of the editors/IDEs has support for that.

The side effects will be minimal for everyone NOT using `.editorconfig`. It does not break anything.
Also if anyone wants to (s)he can download a plugin from http://editorconfig.org/#download

### Help wanted

What do you guys think? Should we go for it?

**Comment by gregbeech** [comment]
We already do in [some projects](https://github.com/deliveroo/logistics-dashboard#ide-setup-editorconfig).

**Comment by tompave-roo** [comment]
I feel against this, at least for our existing large codebases.

I agree that formatting whitespace is important, and I would support the adoption of this kind of common editor configurations for greenfield projects. I'm also aware of the risks of doing it elsewhere.

We have a number of large teams collaborating on the same codebases. This means that two elements of git-based workflows are important for us:
1) PRs and changes must be focussed, precise, isolated and easily revertible. This means that we need to minimize the risk of conflicts or unrelated changes in PRs.
2) Quite often, the ability to easily trace a code change to a specific commit is important. It leads to the PR that introduced the changes, and to the broader context. This of when you need to understand why some code was written in a certain way, and you `git blame` it to find out what else was committed with it.

When code editors start policing and rewriting entire files, however, you will make both diffs and commit histories much harder to follow.

**Comment by xarisd** [comment]
@tompave-roo I totally agree with you, that is why I am suggesting to do it only in non-critical projects (like `deliveroo.engineering`).
Also agree for greenfield projects. That way we are starting to reduce/eliminate these kind of problems.

**Comment by jphastings** [comment]
:+1: I like the sound of this, for projects where it wouldn't make substantial changes when applied.

**Comment by oneKelvinSmith** [comment]
"Add ?w=1 to the URL to see the diff with whitespace ignored." 

https://github.com/blog/967-github-secrets
