### ISSUE TITLE
Contradiction concerning PATCH HTTP status code

### ISSUE THREAD

**Issue by arno-di-loreto** [deliveroo/deliveroo.engineering#135]
It seems there's a contradiction in the guidelines concerning HTTP status codes return by PATCH:

In [PATCH, mutating entities](http://deliveroo.engineering/guidelines/api-design/#patch-mutating-entities)
> 200 OK, if the modification succeeded

In [Return codes and errors](http://deliveroo.engineering/guidelines/api-design/#return-codes-and-errors)
> POST and PATCH should never result in a 200 (generally 201, occasionally 202).

**Comment by m4yankpomelo** [comment]
It looks like they don't care :(

**Comment by jamietanna** [comment]
Thanks for raising, we've removed the guidelines (in #190) as they were woefully out-of-date, but appreciate the feedback 💜
