### ISSUE TITLE
How is the Rider/Restaurant assignment made?

### ISSUE THREAD

**Issue by carlosjoserg** [deliveroo/deliveroo.engineering#153]
Hi devs,

I was just wondering how the process of an assignment of a rider to pick up an order to a restaurant during devliery time is. I couldn't find it in any of the repository, or maybe I missed it. Can someone point  where I can find it, or briefly describe it?

I see you have implementations of the Hungarian algorithm [here](https://github.com/deliveroo/munkres_ru) and [here](https://github.com/deliveroo/hungarian_algorithm_c), and also of the [haversine distance](https://github.com/deliveroo/haversine_distance), so my guess is you use the latter to set the cost of a tuple (rider, restaurant) in the problem matrix, am I right?

Thanks in advance

**Comment by pedrocunha** [comment]
Hi Carlos,

We use all kinds of heuristics to assign orders and riders. They include things like objective functions (also called cost functions), Hungarian and Tabu search (as meta heuristics, you found already a good solution now you iterate further), linear regression models that predict trip durations, food times, rider and order forecast, etc...

We are trying to publish as much as possible our work, but as you probably know we wouldn't want our core algorithms to be public as there are all kinds of fierce competitors :)

I hope this gives you a brief description of some of the stuff we work on, happy to follow up if you have more questions.

Cheers,
Pedro

**Comment by carlosjoserg** [comment]
Hi Pedro,

Thanks very much for the details. Sounds interesting and challenging to manage all that in the assignment.. looks like there might some AI component around then.

> We are trying to publish as much as possible our work, but as you probably know we wouldn't want our core algorithms to be public as there are all kinds of fierce competitors :)

Completely understand ;)

> I hope this gives you a brief description of some of the stuff we work on, happy to follow up if you have more questions

Yes, thanks very much, I appreciate it, some items you mention confirm what I was expecting how this was done.

One last question, if I may, by _rider forecast_ you mean you consider how good a rider has been with certain oders (a particular restaurant for instance), so to assign a current order to one rider or the other?

Best
Carlos

**Comment by pedrocunha** [comment]
Yep, we use a lot of ML to build prediction models. Sorry if I was not clear on forecast. Our algorithms are sensible to several settings of riders and orders, but not to specific individual riders (for example we care about thinks like their vehicle type, but not really to their individual performance)

**Comment by carlosjoserg** [comment]
Alright, thanks!

Hope to see more in the public domain in the future, it's a really interesting problem

Closing the issue..
