### ISSUE TITLE
Partner API response timelines for account?

### ISSUE THREAD

**Issue by AAtticus** [deliveroo/deliveroo.engineering#231]
Hi there Deliveroo Engineering team,

We've been awaiting patiently for an account at https://developers.deliveroo.com/partner-api/introduction for a while now.

We never received any acknowledgement of requesting an account but have filled in the form a couple of times over the last months now. 

What is the expected timelines to hear something back?

**Comment by m4yankpomelo** [comment]
Oh, its same for me, I've been chasing myself to hear back from the engineering team for long enough. Do let me know if you hear back.

**Comment by AAtticus** [comment]
![google-street](https://user-images.githubusercontent.com/1580554/131206511-7bb762c7-4678-44e7-a79c-7bfcea228d7e.gif)

**Comment by m4yankpomelo** [comment]
Nothing yet is it? Do they even exists?

**Comment by AAtticus** [comment]
....

**Comment by m4yankpomelo** [comment]
If you get a response, do reply here, so at-least I know they've an engineering team!

**Comment by jamietanna** [comment]
Sorry folks, this repo isn't to be used for getting support on integrations, and looks like issues generally haven't been too well monitored.
