### ISSUE TITLE
Restore "edit" links

### ISSUE THREAD

**Issue by mezis** [deliveroo/deliveroo.engineering#80]
Before the restyle, we had an "edit" link on all articles & documents, pointing to Github's online edition feature, to allow users to easily fix typos or propose minor changes.

Having this edit link was decided as a group (by the 'roo tech leads) so we'd probably want it back!

**Comment by kapowaz** [comment]
My question would be: how do we get visibility of these edits, if they’re done without review and merged immediately? Directly editing files on github always struck me as a very dangerous feature, so I would always be inclined to encourage people to just open a small pull request and get it merged quickly. So far the workflow we’ve been using hasn’t seemed to be impeded by the absence of direct editing, so I wonder if it’s really necessary?

**Comment by mezis** [comment]
@kapowaz: ah, I get why you were concerned now. Github's feature is _not_ "direct editing". It lets you create commits from a nice user interface.

When "saving", you're prompted to either commit to the master branch (which is disabled for non-admin users on this repo), or create a branch and issue a PR (which would be fine for us).

Think of this as lowering the barrier to small edits:

- Read an article.
- Spot a typo / bad phrasing / required clarification.
- Click the link, edit, submit PR in a handful of clicks.

![](https://www.dropbox.com/s/rrep5xf8204b93n/2016-10-13%20pr%20demo.gif?raw=1)

> So far the workflow we’ve been using hasn’t seemed to be impeded by the absence of direct editing, so I wonder if it’s really necessary?

"So far". Having managed a blog for a large team before, and struggling to get contributions, I can promise you this: anything that lowers the barrier is a good thing.

**Comment by kapowaz** [comment]
@mezis ah, that’s different then. If we protect the `gh-pages` branch, does that prevent committing directly from that interface (i.e. forcing people to use the _create a new branch_ option)?

I’m assuming that unless you’re a contributor on this repo, you can’t do this at all (i.e. general members of the public wouldn’t have the ability to even create a new branch/PR this way)?
